# Generated by Django 4.2.20 on 2025-04-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Verhaal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('tekst', models.TextField()),
                ('is_onzichtbaar', models.BooleanField(default=False)),
                ('beschrijving', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='verhalen_covers/')),
                ('datum', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verhalen.categorie')),
            ],
        ),
    ]
