# Generated by Django 5.2 on 2025-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verhalen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verhaal",
            name="is_spotlighted",
            field=models.BooleanField(default=False),
        ),
    ]
