# Generated by Django 4.2.11 on 2025-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhalen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='is_uitgelicht',
            field=models.BooleanField(default=False),
        ),
    ]
