# Generated by Django 4.2.11 on 2025-04-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhalen', '0002_categorie_is_uitgelicht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='categorie_covers/'),
        ),
        migrations.AlterField(
            model_name='verhaal',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='verhalen_covers/'),
        ),
    ]
