# Generated by Django 5.2 on 2025-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verhalen", "0003_verhaal_is_downloadable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verhaal",
            name="beschrijving",
            field=models.CharField(max_length=500),
        ),
    ]
