# Generated by Django 4.2.11 on 2025-05-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhalen', '0004_alter_verhaal_beschrijving'),
    ]

    operations = [
        migrations.AddField(
            model_name='verhaal',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='verhalen_pdfs/'),
        ),
    ]
