# Generated by Django 4.2.11 on 2025-05-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verhalen', '0005_verhaal_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verhaal',
            old_name='pdf_file',
            new_name='word_file',
        ),
    ]
