# Generated by Django 4.2.11 on 2025-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhalen', '0006_rename_pdf_file_verhaal_word_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='verhaal',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='verhalen_pdfs/pdf/'),
        ),
        migrations.AlterField(
            model_name='verhaal',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='verhalen_pdfs/docx/'),
        ),
    ]
