# Generated by Django 4.2.11 on 2025-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhalen', '0007_verhaal_pdf_file_alter_verhaal_word_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='verhaal',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='verhaal',
            name='beschrijving',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
