# Generated by Django 4.2.11 on 2025-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verhalen', '0008_verhaal_url_alter_verhaal_beschrijving'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='beschrijving',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
