# Generated by Django 4.2.11 on 2025-05-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Overmij',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitel', models.CharField(max_length=200)),
                ('tekst', models.TextField()),
                ('afbeelding', models.ImageField(blank=True, null=True, upload_to='overmij_afbeelding/')),
            ],
        ),
    ]
