# Generated by Django 4.2.11 on 2025-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overmijpagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
